### ISSUE TITLE
"Error" project path "libbabmbuser" couldnot found

### ISSUE THREAD

**Issue by VIRGO96** [bambuser/react-native-bambuser-broadcaster#2]
I am having rough time understanding the docs if anyone here could help me out what this line means and why do we need to add a subproject this line in docs i have pasted below
**Important note: when adding the libbambuser subproject, make sure you name it libbambuser, the React Native component will look for this subproject when building your React Native app.**

**Comment by peterlofquist** [comment]
In order to use our react-native-bambuser-broadcaster component you'll have to include our SDK to your react-native project as well. When including the SDK to your project refer to [this guide, add-the-broadcast-sdk](https://bambuser.com/docs/broadcasting/android/#add-the-broadcast-sdk).

In the step where you import the `.aar` SDK file Android Studio will default the name of the to be imported module to something like `libbambuser-android-0.9.15`. At this point it's important to use the module name `libbambuser` instead, as that's what some build files will look for when compiling the code.
