### ISSUE TITLE
Unable to open the camera view but broadcast was working.

### ISSUE THREAD

**Issue by NareshMedipally** [bambuser/react-native-bambuser-broadcaster#25]
When tried to call startBroadcast() method, I'm unable to open the camera view on iOS whereas the broadcast is started and I'm able to see in bambuser console. Is there anything that I'm missing in terms of configuration? Below are the versions
react-native-cli: 2.0.1
react-native: 0.61.5

Thanks in advance :)

**Comment by peterlofquist** [comment]
Hi, and thanks for the issue report!

Have you tried to set a size to the react-native-bambuser-broadcaster component? It sounds like in your description that the instance is available but maybe isn't rendered because you have not given it a size yet.

If that doesn't work, could you then send some example code to help me reproduce this issue? :-) Many thanks!

**Comment by NareshMedipally** [comment]
Thanks @peterlofquist, Forgot to set the size of the component.Able to see it now :)

**Comment by karanpratapsingh** [comment]
@NareshMedipally hey this helped me, however I'm not able to start the broadcast, when i call . startBroadcast() method I cannot see anything on the dashboard, could you share which props are necessary for that, that'd be huge help. 
Thank you

**Comment by NareshMedipally** [comment]
@karanpratapsingh  In terms of props I have passed reference,applicationId to the RNBambuserBroadcaster component.

Have you created standalone project or cloned from  [(https://github.com/bambuser/react-native-bambuser-broadcaster)]?
